name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Следит за пушами в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Создание .nojekyll
        run: |
          touch docs/.nojekyll
          git add docs/.nojekyll
          git commit -m "Disable Jekyll"
          git push

      - name: Деплой в GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
