name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Следит за пушами в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Создание .nojekyll (если нужно)
        run: |
          echo > docs/.nojekyll  # Создаем пустой файл .nojekyll
          git add docs/.nojekyll
          git commit -m "Add .nojekyll" || echo "No changes"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Папка с файлами для деплоя
